version: "3.5"

# Configuración de redes

networks:
  frontend:
    ipam:
      config:
        - subnet: 192.168.96.0/24

# Servidor nginx

services:

  sweb1:
    image: docker.io/wyveo/nginx-php-fpm
    ports:
      - "85:85"
      - "443:443"
    container_name: nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certificados/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./certificados/key.pem:/etc/nginx/conf.d/key.pem
    networks:
        frontend:
            ipv4_address: 192.168.96.3

# Servidor apache2

  sweb2:
    image: docker.io/krishnapanchalguddu/apache2-php8.1
    ports:
      - "80:80"
    container_name: apache2
    volumes:
      - ./src:/var/www/html
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2/app.conf:/etc/apache2/sites-enabled/app.conf
      # - ./certificados/cert.pem:/etc/ssl/certs/cert.pem
      # - ./certificados/key.pem:/etc/ssl/certs/key.pem
    networks:
        frontend:
            ipv4_address: 192.168.96.2

# Configuración de mysql

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Petrisor
      MYSQL_DATABASE: sarabastall
      MYSQL_USER: sarab
      MYSQL_PASSWORD: baras
    ports:
      - 3306:3306
    volumes:
      - ./database/_data:/var/lib/mysql
    networks:
        frontend:
            ipv4_address: 192.168.96.4

  # Configuración de phpmyadmin 

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
        frontend:
            ipv4_address: 192.168.96.5
